In [2]:
from sklearn import tree
import pandas as pd
import os
from zipfile import ZipFile

In [4]:
i=("Data/stormdata.zip")

zf = ZipFile(i)
    
name = zf.namelist()[0]

print(name)

df = pd.read_csv(zf.open(name))

stormdata.csv

In [5]:
df.head()

,Start Date_st,End Date_st,Name_st,State_st,Category_st,Central Pressure_st,Max Wind (Kt)_st,Date,Location,MM,...,Longitude,Latitude,MWD(deg),PRES(T hPa),R WSP(T m/s),TIDE(ft),VIS(mi),WDI deg,WTMP(Cel),WVHT(m)
0,7/14/2019,7/16/2019,Barry,LA 2,2.0,993,90,7/14/2019,208 NM West of Naples FL ...,Jul,...,25.925,-85.615,999,1016.5,6.0,99,99,118,28.6,99.0
1,7/15/2019,7/16/2019,Barry,LA 2,2.0,993,90,7/15/2019,208 NM West of Naples FL ...,Jul,...,25.925,-85.615,999,1018.1,5.7,99,99,117,28.9,99.0
2,7/16/2019,7/16/2019,Barry,LA 2,2.0,993,90,7/16/2019,208 NM West of Naples FL ...,Jul,...,25.925,-85.615,999,1017.8,6.4,99,99,91,29.4,99.0
3,7/13/2019,7/16/2019,Barry,LA 2,2.0,993,90,7/13/2019,208 NM West of Naples FL ...,Jul,...,25.925,-85.615,999,1013.8,8.6,99,99,181,29.4,99.0
4,7/12/2019,7/16/2019,Barry,LA 2,2.0,993,90,7/12/2019,208 NM West of Naples FL ...,Jul,...,25.925,-85.615,999,1012.0,8.4,99,99,213,29.7,99.0

In [6]:
len(df.index)

106740

In [35]:
list(df.columns)

['Start Date_st',
 'End Date_st',
 'Name_st',
 'State_st',
 'Category_st',
 'Central Pressure_st',
 'Max Wind (Kt)_st',
 'Date',
 'Location',
 'MM',
 'Sector',
 'Station',
 '#YY',
 'APD(sec)',
 'ATMP(Cel)',
 'Hh',
 'Min',
 'D GST(m/s)',
 'DEWP(Cel)',
 'DPD(sec)',
 'Longitude',
 'Latitude',
 'MWD(deg)',
 'PRES(T hPa)',
 'R WSP(T m/s)',
 'TIDE(ft)',
 'VIS(mi)',
 'WDI deg',
 'WTMP(Cel)',
 'WVHT(m)']

In [19]:
target = df["Category_st"].astype(str)

In [36]:
data = df[["R WSP(T m/s)", "WTMP(Cel)", "WVHT(m)"]]
feature_names = data.columns
data.head()

   R WSP(T m/s)  WTMP(Cel)  WVHT(m)
0           6.0       28.6     99.0
1           5.7       28.9     99.0
2           6.4       29.4     99.0
3           8.6       29.4     99.0
4           8.4       29.7     99.0

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.80, random_state=42)

In [38]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.4778902004871651

In [39]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.5150014052838673

In [40]:
sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.3787397704901473, 'R WSP(T m/s)'),
 (0.34914193961111983, 'WTMP(Cel)'),
 (0.272118289898733, 'WVHT(m)')]

In [54]:
df_test=pd.read_csv("8_2020.csv")

In [50]:
df_test.head()

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2020,8,20,0,0,203,4.1,5.0,99.00,99.0,99.00,999,1011.5,999,30.6,999,99,467.630882
1,2020,8,20,0,10,206,3.2,4.5,99.00,99.0,99.00,999,1011.6,999,30.7,999,99,467.316912
2,2020,8,20,0,20,195,3.1,4.1,99.00,99.0,99.00,999,1011.6,999,30.4,999,99,467.030147
3,2020,8,20,0,30,191,3.2,4.0,99.00,99.0,99.00,999,1011.7,999,30.4,999,99,466.777941
4,2020,8,20,0,40,200,2.8,4.0,0.19,99.0,4.13,999,1011.9,999,30.4,999,99,450.862794

In [43]:
list(df_test.columns)

['#YY',
 'MM',
 'DD',
 'hh',
 'mm',
 'WDIR',
 'WSPD',
 'GST',
 'WVHT',
 'DPD',
 'APD',
 'MWD',
 'PRES',
 'ATMP',
 'WTMP',
 'DEWP',
 'VIS',
 'TIDE']

In [53]:
aug_24=df_test.loc[df_test["DD"]==24]
aug_24.head(10)

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
576,2020,8,24,0,0,999,6,7.7,99.00,99.00,99.00,999,1010.9,999,29.4,999,99,461.293382
577,2020,8,24,0,10,999,6.2,8.0,99.00,99.00,99.00,999,1011.0,999,29.4,999,99,461.027941
578,2020,8,24,0,20,999,6.3,8.2,99.00,99.00,99.00,999,1011.3,999,29.4,999,99,460.786765
579,2020,8,24,0,30,999,5.9,7.6,99.00,99.00,99.00,999,1011.4,999,29.5,999,99,460.498529
580,2020,8,24,0,40,999,5.6,7.0,2.03,7.14,5.72,126,1011.5,999,29.5,999,99,328.331323
581,2020,8,24,0,50,999,5.6,7.4,99.00,99.00,99.00,999,1011.5,999,29.6,999,99,459.932353
582,2020,8,24,1,0,999,5.5,7.1,99.00,99.00,99.00,999,1011.7,999,29.6,999,99,461.368382
583,2020,8,24,1,10,999,5,6.6,99.00,99.00,99.00,999,1011.8,999,29.6,999,99,461.063235
584,2020,8,24,1,20,999,4.4,5.8,99.00,99.00,99.00,999,1011.9,999,29.6,999,99,460.745588
585,2020,8,24,1,30,999,6.5 1,0.8,99.00,99.00,99.00,999,1012.0,999,29.6,999,99,7.466667

In [47]:
# Create an empty list 
test_values =[] 
  
# Iterate over each row 
for index, rows in aug_24.iterrows(): 
    # Create list for the current row 
    my_list =[rows.WSPD, rows.WTMP, rows.WVHT] 
      
    # append the list to the final list 
    test_values.append(my_list) 
  
# Print the list 
print(test_values)

[['6', 29.4, 99.0], ['6.2', 29.4, 99.0], ['6.3', 29.4, 99.0], ['5.9', 29.5, 99.0], ['5.6', 29.5, 2.03], ['5.6', 29.6, 99.0], ['5.5', 29.6, 99.0], ['5', 29.6, 99.0], ['4.4', 29.6, 99.0], ['6.5 1', 29.6, 99.0], ['9.1 1', 29.6, 1.94], ['9.5 1', 29.6, 99.0], ['9.4 1', 29.6, 99.0], ['9.3 1', 29.6, 99.0], ['9.4 1', 29.6, 99.0], ['9.1 1', 29.6, 99.0], ['9.4 1', 29.6, 1.82], ['9.3 1', 29.6, 99.0], ['9.3 1', 29.6, 99.0], ['8.7 1', 29.6, 99.0], ['8.7 1', 29.6, 99.0], ['8.5 1', 29.6, 99.0], ['8.9 1', 29.6, 1.76], ['8.6 1', 29.6, 99.0], ['8.6 1', 29.5, 99.0], ['8.8 1', 29.5, 99.0], ['9.2 1', 29.4, 99.0], ['9.0 1', 29.4, 99.0], ['9.1 1', 29.5, 1.64], ['8.9 1', 29.5, 99.0], ['9.2 1', 29.5, 99.0], ['8.7 1', 29.5, 99.0], ['9.0 1', 29.5, 99.0], ['8.8 1', 29.5, 99.0], ['8.6 1', 29.5, 1.65], ['8.6 1', 29.5, 99.0], ['8.5 1', 29.5, 99.0], ['8.2 1', 29.5, 99.0], ['8.4 1', 29.5, 99.0], ['7.8', 29.5, 99.0], ['7.8', 29.5, 1.49], ['7.7', 29.5, 99.0], ['7.8', 29.5, 99.0], ['7.5', 29.5, 99.0], ['7', 29.5, 99.0], ['7.2', 29.6, 99.0], ['6.8', 29.6, 1.52], ['6.4', 29.6, 99.0], ['6.5', 29.6, 99.0], ['7.3', 29.6, 99.0], ['6.8', 29.6, 99.0], ['6.4', 29.6, 99.0], ['6.9', 29.6, 1.23], ['6.4', 29.6, 99.0], ['6.4', 29.5, 99.0], ['6.8', 29.5, 99.0], ['6.5', 29.5, 99.0], ['6.3', 29.4, 99.0], ['6.3', 29.4, 1.25], ['5.8', 29.4, 99.0], ['5.7', 29.4, 99.0], ['5.4', 29.4, 99.0], ['5.6', 29.4, 99.0], ['5.3', 29.4, 99.0], ['5.3', 29.4, 1.09], ['5.1', 29.4, 99.0], ['5.2', 29.4, 99.0], ['5.1', 29.4, 99.0], ['4.9', 29.4, 99.0], ['5', 29.4, 99.0], ['4.9', 29.3, 1.02], ['4.7', 29.3, 99.0], ['4.8', 29.3, 99.0], ['4.8', 29.2, 99.0], ['4.6', 29.1, 99.0], ['4.6', 29.1, 99.0], ['4.2', 29.1, 0.93], ['4.6', 29.1, 99.0], ['4.7', 29.1, 99.0], ['4.6', 29.1, 99.0], ['4.2', 29.1, 99.0], ['5.1', 29.1, 99.0], ['5.3', 29.1, 0.82], ['3.9', 29.1, 99.0], ['3.3', 29.1, 99.0], ['2.9', 29.1, 99.0], ['2.9', 29.1, 99.0], ['2.8', 29.1, 99.0], ['3.7', 29.2, 0.87], ['3.5', 29.2, 99.0], ['3.3', 29.2, 99.0], ['3.3', 29.2, 99.0], ['3.6', 29.3, 99.0], ['3.5', 29.3, 99.0], ['3.2', 29.3, 0.84], ['3.4', 29.3, 99.0], ['3.6', 29.2, 99.0], ['3.2', 29.4, 99.0], ['3.5', 29.3, 99.0], ['3.4', 29.3, 99.0], ['4', 29.3, 0.78], ['4.4', 29.2, 99.0], ['4.2', 29.3, 99.0], ['3.8', 29.4, 99.0], ['3.6', 29.4, 99.0], ['5.3', 29.4, 99.0], ['6.3', 29.4, 0.94], ['5.5', 29.4, 99.0], ['3.3', 29.4, 99.0], ['3.2', 29.4, 99.0], ['2.9', 29.5, 99.0]]

In [48]:
clf.predict(test_values)

ValueError: could not convert string to float: '6.5 1'